tasks:
  - before: npm i -g npm && npm i .
    init: npm i -g @zowe/cli
          zowe plugins install @zowe/zos-ftp-for-zowe-cli &&
          zowe plugins install @broadcom/endevor-bridge-for-git-for-zowe-cli &&
          zowe plugins install @broadcom/endevor-for-zowe-cli &&
          zowe profiles create zosmf zcobol-zosmf --hostname $zcobol_hostname --port $zcobol_port --username $zcobol_username --password $zcobol_password --ru false &&
          zowe profiles create zftp zcobol-zftp --hostname $zcobol_hostname --port 21 --username $zcobol_username --password $zcobol_password --ru false
vscode:
  extensions:
    - zowe.vscode-extension-for-zowe
    - zowe.zowe-explorer-ftp-extensionS
    - broadcommfd.code4z-extension-pack
    - eamodio.gitlens
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - visualstudioexptteam.vscodeintellicode
    - dbaeumer.vscode-eslint
    - orta.vscode-jest
